site_name: C++ Lambda Story
site_url: https://nolongerwait.github.io/cpp_lambda_story_chinese_edition/
site_author: nolongerwait
site_description: >-
  C++ Lambda Story

# Repository
repo_name: cpp-lambda-story-chinese-edition
repo_url: https://github.com/nolongerwait/cpp_lambda_story_chinese_edition
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2022 <a href="https://github.com/nolongerwait" target="_blank" rel="noopener noreferrer">nolongerwait</a>

# Configuration
theme:
  name: material
  custom_dir: theme

  # Static files
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: zh

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    - toc.integrate
    - content.code.annotate

    # insiders only
    # - content.tabs.link

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: dracula
      primary: deep purple
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/1200px-ISO_C++_Logo.svg.png
  icon:
    repo: fontawesome/brands/github
  logo: assets/1200px-ISO_C++_Logo.svg.png

# Plugins
plugins:
  - search:
      lang: ja
  - git-revision-date-localized:
      type: date
      enable_creation_date: true
  - minify:
      minify_html: true
  - mkdocs-material-extras:

# Customization
extra:
  generator: false
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/nolongerwait/cpp_lambda_story_chinese_edition

# Extensions
markdown_extensions:
  - admonition:
  - abbr:
  - attr_list:
  - def_list:
  - footnotes:
  - md_in_html:
  - meta:
  - markdown.extensions.smarty:
      smart_quotes: false
  - markdown.extensions.tables:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
      toc_depth: 3
  - pymdownx.arithmatex:
  - pymdownx.betterem:
  - pymdownx.caret:
  - pymdownx.critic:
  - pymdownx.keys:
  - pymdownx.tilde:
  - pymdownx.mark:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
      linenums_style: pymdownx-inline
      anchor_linenums: true
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.magiclink:
      repo_url_shortener: true
      repo_url_shorthand: true
      social_url_shorthand: true
      social_url_shortener: true
      normalize_issue_symbols: true
  - pymdownx.smartsymbols:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: false
  - pymdownx.escapeall:
      hardbreak: true
      nbsp: true
  - pymdownx.progressbar:
  - pymdownx.striphtml:
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.saneheaders:

docs_dir: Source

nav:
  - Getting Started: index.md
  - 关于此书: Chapter0/README.md
  - Lambda in C++98/03: Chapter1/README.md
  - Lambda in C++11: Chapter2/README.md
  - Lambda in C++14: Chapter3/README.md
  - Lambda in C++17: Chapter4/README.md
  - Lambda in C++20: Chapter5/README.md
